### ISSUE TITLE
Add option to download using  file id

### ISSUE THREAD

**Issue by rafiibrahim8** [rafiibrahim8/gddl#2]
Currently gddl takes url like `https://drive.google.com/files/d/<file id>` then extract file id using regex to download the file. 

It will be a nice feature to input just the id and get the file downloaded.
E.g:
`gddl abcd1234`

**Comment by mueid20** [comment]
I wanna do it

**Comment by rafiibrahim8** [comment]
@mueid20 Okay. Waiting for your PR.
